# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from proto.gRPCCommunication.GrpcProtoType_pb2 import (
    GrpcProtoType as proto___gRPCCommunication___GrpcProtoType_pb2___GrpcProtoType,
)

from typing import (
    Iterable as typing___Iterable,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class GrpcStepOutput(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class InfoEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key = ... # type: typing___Text
        value = ... # type: builtin___bytes

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[builtin___bytes] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GrpcStepOutput.InfoEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"key",u"value"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    stringObervations = ... # type: typing___Text
    floatObervations = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___float]
    intObervations = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[builtin___int]
    reward = ... # type: builtin___float
    done = ... # type: builtin___bool

    @property
    def info(self) -> typing___MutableMapping[typing___Text, builtin___bytes]: ...

    @property
    def obervationType(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___gRPCCommunication___GrpcProtoType_pb2___GrpcProtoType]: ...

    @property
    def infoType(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___gRPCCommunication___GrpcProtoType_pb2___GrpcProtoType]: ...

    def __init__(self,
        *,
        stringObervations : typing___Optional[typing___Text] = None,
        floatObervations : typing___Optional[typing___Iterable[builtin___float]] = None,
        intObervations : typing___Optional[typing___Iterable[builtin___int]] = None,
        reward : typing___Optional[builtin___float] = None,
        done : typing___Optional[builtin___bool] = None,
        info : typing___Optional[typing___Mapping[typing___Text, builtin___bytes]] = None,
        obervationType : typing___Optional[typing___Iterable[proto___gRPCCommunication___GrpcProtoType_pb2___GrpcProtoType]] = None,
        infoType : typing___Optional[typing___Iterable[proto___gRPCCommunication___GrpcProtoType_pb2___GrpcProtoType]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> GrpcStepOutput: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"done",u"floatObervations",u"info",u"infoType",u"intObervations",u"obervationType",u"reward",u"stringObervations"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"done",b"done",u"floatObervations",b"floatObervations",u"info",b"info",u"infoType",b"infoType",u"intObervations",b"intObervations",u"obervationType",b"obervationType",u"reward",b"reward",u"stringObervations",b"stringObervations"]) -> None: ...
