# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpcPackage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.gRPCCommunication import GrpcHeader_pb2 as proto_dot_gRPCCommunication_dot_GrpcHeader__pb2
from proto.gRPCCommunication import GrpcStepInput_pb2 as proto_dot_gRPCCommunication_dot_GrpcStepInput__pb2
from proto.gRPCCommunication import GrpcStepOutput_pb2 as proto_dot_gRPCCommunication_dot_GrpcStepOutput__pb2
from proto.gRPCCommunication import GrpcParameter_pb2 as proto_dot_gRPCCommunication_dot_GrpcParameter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpcPackage.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)proto/gRPCCommunication/GrpcPackage.proto\x12\x11gRPCCommunication\x1a(proto/gRPCCommunication/GrpcHeader.proto\x1a+proto/gRPCCommunication/GrpcStepInput.proto\x1a,proto/gRPCCommunication/GrpcStepOutput.proto\x1a+proto/gRPCCommunication/GrpcParameter.proto\"\xde\x01\n\x0bGrpcPackage\x12-\n\x06header\x18\x01 \x01(\x0b\x32\x1d.gRPCCommunication.GrpcHeader\x12/\n\x05input\x18\x02 \x01(\x0b\x32 .gRPCCommunication.GrpcStepInput\x12\x31\n\x06output\x18\x03 \x01(\x0b\x32!.gRPCCommunication.GrpcStepOutput\x12<\n\x12trainingParameters\x18\x04 \x03(\x0b\x32 .gRPCCommunication.GrpcParameterb\x06proto3')
  ,
  dependencies=[proto_dot_gRPCCommunication_dot_GrpcHeader__pb2.DESCRIPTOR,proto_dot_gRPCCommunication_dot_GrpcStepInput__pb2.DESCRIPTOR,proto_dot_gRPCCommunication_dot_GrpcStepOutput__pb2.DESCRIPTOR,proto_dot_gRPCCommunication_dot_GrpcParameter__pb2.DESCRIPTOR,])




_GRPCPACKAGE = _descriptor.Descriptor(
  name='GrpcPackage',
  full_name='gRPCCommunication.GrpcPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='gRPCCommunication.GrpcPackage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input', full_name='gRPCCommunication.GrpcPackage.input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='gRPCCommunication.GrpcPackage.output', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trainingParameters', full_name='gRPCCommunication.GrpcPackage.trainingParameters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=465,
)

_GRPCPACKAGE.fields_by_name['header'].message_type = proto_dot_gRPCCommunication_dot_GrpcHeader__pb2._GRPCHEADER
_GRPCPACKAGE.fields_by_name['input'].message_type = proto_dot_gRPCCommunication_dot_GrpcStepInput__pb2._GRPCSTEPINPUT
_GRPCPACKAGE.fields_by_name['output'].message_type = proto_dot_gRPCCommunication_dot_GrpcStepOutput__pb2._GRPCSTEPOUTPUT
_GRPCPACKAGE.fields_by_name['trainingParameters'].message_type = proto_dot_gRPCCommunication_dot_GrpcParameter__pb2._GRPCPARAMETER
DESCRIPTOR.message_types_by_name['GrpcPackage'] = _GRPCPACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcPackage = _reflection.GeneratedProtocolMessageType('GrpcPackage', (_message.Message,), {
  'DESCRIPTOR' : _GRPCPACKAGE,
  '__module__' : 'proto.gRPCCommunication.GrpcPackage_pb2'
  # @@protoc_insertion_point(class_scope:gRPCCommunication.GrpcPackage)
  })
_sym_db.RegisterMessage(GrpcPackage)


# @@protoc_insertion_point(module_scope)
