# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpcProtoType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpcProtoType.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+proto/gRPCCommunication/GrpcProtoType.proto\x12\x11gRPCCommunication\"U\n\rGrpcProtoType\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.gRPCCommunication.GrpcBaseProtoType\x12\x10\n\x08repeated\x18\x02 \x01(\x08*\xc7\x01\n\x11GrpcBaseProtoType\x12\n\n\x06\x44OUBLE\x10\x00\x12\t\n\x05\x46LOAT\x10\x01\x12\t\n\x05INT32\x10\x02\x12\t\n\x05INT64\x10\x03\x12\n\n\x06UINT32\x10\x04\x12\n\n\x06UINT64\x10\x05\x12\n\n\x06SINT32\x10\x06\x12\n\n\x06SINT64\x10\x07\x12\x0b\n\x07\x46IXED32\x10\x08\x12\x0b\n\x07\x46IXED64\x10\t\x12\x0c\n\x08SFIXED32\x10\n\x12\x0c\n\x08SFIXED64\x10\x0b\x12\x08\n\x04\x42OOL\x10\x0c\x12\n\n\x06STRING\x10\r\x12\t\n\x05\x42YTES\x10\x0e\x62\x06proto3')
)

_GRPCBASEPROTOTYPE = _descriptor.EnumDescriptor(
  name='GrpcBaseProtoType',
  full_name='gRPCCommunication.GrpcBaseProtoType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT32', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT64', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT32', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UINT64', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINT32', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SINT64', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXED32', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXED64', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SFIXED32', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SFIXED64', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=12, number=12,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=13, number=13,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BYTES', index=14, number=14,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=154,
  serialized_end=353,
)
_sym_db.RegisterEnumDescriptor(_GRPCBASEPROTOTYPE)

GrpcBaseProtoType = enum_type_wrapper.EnumTypeWrapper(_GRPCBASEPROTOTYPE)
DOUBLE = 0
FLOAT = 1
INT32 = 2
INT64 = 3
UINT32 = 4
UINT64 = 5
SINT32 = 6
SINT64 = 7
FIXED32 = 8
FIXED64 = 9
SFIXED32 = 10
SFIXED64 = 11
BOOL = 12
STRING = 13
BYTES = 14



_GRPCPROTOTYPE = _descriptor.Descriptor(
  name='GrpcProtoType',
  full_name='gRPCCommunication.GrpcProtoType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='gRPCCommunication.GrpcProtoType.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repeated', full_name='gRPCCommunication.GrpcProtoType.repeated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=151,
)

_GRPCPROTOTYPE.fields_by_name['type'].enum_type = _GRPCBASEPROTOTYPE
DESCRIPTOR.message_types_by_name['GrpcProtoType'] = _GRPCPROTOTYPE
DESCRIPTOR.enum_types_by_name['GrpcBaseProtoType'] = _GRPCBASEPROTOTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcProtoType = _reflection.GeneratedProtocolMessageType('GrpcProtoType', (_message.Message,), {
  'DESCRIPTOR' : _GRPCPROTOTYPE,
  '__module__' : 'proto.gRPCCommunication.GrpcProtoType_pb2'
  # @@protoc_insertion_point(class_scope:gRPCCommunication.GrpcProtoType)
  })
_sym_db.RegisterMessage(GrpcProtoType)


# @@protoc_insertion_point(module_scope)
