# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto.gRPCCommunication import GrpcPackage_pb2 as proto_dot_gRPCCommunication_dot_GrpcPackage__pb2


class GrpcCommunicatorStub(object):
  """The GrpcCommunicator service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Communicate = channel.unary_unary(
        '/gRPCCommunication.GrpcCommunicator/Communicate',
        request_serializer=proto_dot_gRPCCommunication_dot_GrpcPackage__pb2.GrpcPackage.SerializeToString,
        response_deserializer=proto_dot_gRPCCommunication_dot_GrpcPackage__pb2.GrpcPackage.FromString,
        )


class GrpcCommunicatorServicer(object):
  """The GrpcCommunicator service definition.
  """

  def Communicate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GrpcCommunicatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Communicate': grpc.unary_unary_rpc_method_handler(
          servicer.Communicate,
          request_deserializer=proto_dot_gRPCCommunication_dot_GrpcPackage__pb2.GrpcPackage.FromString,
          response_serializer=proto_dot_gRPCCommunication_dot_GrpcPackage__pb2.GrpcPackage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'gRPCCommunication.GrpcCommunicator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
