# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class GrpcPPOSettings(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    numAction = ... # type: builtin___int
    valueFactor = ... # type: builtin___float
    entropyFactor = ... # type: builtin___float
    epsilon = ... # type: builtin___float
    learningRate = ... # type: builtin___float
    learningRateDecay = ... # type: typing___Text
    grapClip = ... # type: builtin___float
    loadEpisodeSaved = ... # type: builtin___float
    savedEpisode = ... # type: builtin___float
    timeHozizon = ... # type: builtin___float
    batchSize = ... # type: builtin___float
    gamma = ... # type: builtin___float
    lam = ... # type: builtin___float
    epoch = ... # type: builtin___int
    actors = ... # type: builtin___int
    finalStep = ... # type: builtin___int

    def __init__(self,
        *,
        numAction : typing___Optional[builtin___int] = None,
        valueFactor : typing___Optional[builtin___float] = None,
        entropyFactor : typing___Optional[builtin___float] = None,
        epsilon : typing___Optional[builtin___float] = None,
        learningRate : typing___Optional[builtin___float] = None,
        learningRateDecay : typing___Optional[typing___Text] = None,
        grapClip : typing___Optional[builtin___float] = None,
        loadEpisodeSaved : typing___Optional[builtin___float] = None,
        savedEpisode : typing___Optional[builtin___float] = None,
        timeHozizon : typing___Optional[builtin___float] = None,
        batchSize : typing___Optional[builtin___float] = None,
        gamma : typing___Optional[builtin___float] = None,
        lam : typing___Optional[builtin___float] = None,
        epoch : typing___Optional[builtin___int] = None,
        actors : typing___Optional[builtin___int] = None,
        finalStep : typing___Optional[builtin___int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> GrpcPPOSettings: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"actors",u"batchSize",u"entropyFactor",u"epoch",u"epsilon",u"finalStep",u"gamma",u"grapClip",u"lam",u"learningRate",u"learningRateDecay",u"loadEpisodeSaved",u"numAction",u"savedEpisode",u"timeHozizon",u"valueFactor"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"actors",b"actors",u"batchSize",b"batchSize",u"entropyFactor",b"entropyFactor",u"epoch",b"epoch",u"epsilon",b"epsilon",u"finalStep",b"finalStep",u"gamma",b"gamma",u"grapClip",b"grapClip",u"lam",b"lam",u"learningRate",b"learningRate",u"learningRateDecay",b"learningRateDecay",u"loadEpisodeSaved",b"loadEpisodeSaved",u"numAction",b"numAction",u"savedEpisode",b"savedEpisode",u"timeHozizon",b"timeHozizon",u"valueFactor",b"valueFactor"]) -> None: ...
