# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from proto.gRPCCommunication.GrpcHeader_pb2 import (
    GrpcHeader as proto___gRPCCommunication___GrpcHeader_pb2___GrpcHeader,
)

from proto.gRPCCommunication.GrpcParameter_pb2 import (
    GrpcParameter as proto___gRPCCommunication___GrpcParameter_pb2___GrpcParameter,
)

from proto.gRPCCommunication.GrpcStepInput_pb2 import (
    GrpcStepInput as proto___gRPCCommunication___GrpcStepInput_pb2___GrpcStepInput,
)

from proto.gRPCCommunication.GrpcStepOutput_pb2 import (
    GrpcStepOutput as proto___gRPCCommunication___GrpcStepOutput_pb2___GrpcStepOutput,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class GrpcPackage(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def header(self) -> proto___gRPCCommunication___GrpcHeader_pb2___GrpcHeader: ...

    @property
    def input(self) -> proto___gRPCCommunication___GrpcStepInput_pb2___GrpcStepInput: ...

    @property
    def output(self) -> proto___gRPCCommunication___GrpcStepOutput_pb2___GrpcStepOutput: ...

    @property
    def trainingParameters(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[proto___gRPCCommunication___GrpcParameter_pb2___GrpcParameter]: ...

    def __init__(self,
        *,
        header : typing___Optional[proto___gRPCCommunication___GrpcHeader_pb2___GrpcHeader] = None,
        input : typing___Optional[proto___gRPCCommunication___GrpcStepInput_pb2___GrpcStepInput] = None,
        output : typing___Optional[proto___gRPCCommunication___GrpcStepOutput_pb2___GrpcStepOutput] = None,
        trainingParameters : typing___Optional[typing___Iterable[proto___gRPCCommunication___GrpcParameter_pb2___GrpcParameter]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> GrpcPackage: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"header",u"input",u"output"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"header",u"input",u"output",u"trainingParameters"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"header",b"header",u"input",b"input",u"output",b"output"]) -> builtin___bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"header",b"header",u"input",b"input",u"output",b"output",u"trainingParameters",b"trainingParameters"]) -> None: ...
