# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpcStepInput.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpcStepInput.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+proto/gRPCCommunication/GrpcStepInput.proto\x12\x11gRPCCommunication\" \n\rGrpcStepInput\x12\x0f\n\x07\x61\x63tions\x18\x01 \x03(\x02\x62\x06proto3')
)




_GRPCSTEPINPUT = _descriptor.Descriptor(
  name='GrpcStepInput',
  full_name='gRPCCommunication.GrpcStepInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actions', full_name='gRPCCommunication.GrpcStepInput.actions', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['GrpcStepInput'] = _GRPCSTEPINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcStepInput = _reflection.GeneratedProtocolMessageType('GrpcStepInput', (_message.Message,), {
  'DESCRIPTOR' : _GRPCSTEPINPUT,
  '__module__' : 'proto.gRPCCommunication.GrpcStepInput_pb2'
  # @@protoc_insertion_point(class_scope:gRPCCommunication.GrpcStepInput)
  })
_sym_db.RegisterMessage(GrpcStepInput)


# @@protoc_insertion_point(module_scope)
