# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from proto.gRPCCommunication.GrpCommandType_pb2 import (
    GrpCommandType as proto___gRPCCommunication___GrpCommandType_pb2___GrpCommandType,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


class GrpcHeader(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    magicNumber = ... # type: builtin___int
    status = ... # type: builtin___int
    commandTypes = ... # type: proto___gRPCCommunication___GrpCommandType_pb2___GrpCommandType

    def __init__(self,
        *,
        magicNumber : typing___Optional[builtin___int] = None,
        status : typing___Optional[builtin___int] = None,
        commandTypes : typing___Optional[proto___gRPCCommunication___GrpCommandType_pb2___GrpCommandType] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: builtin___bytes) -> GrpcHeader: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"commandTypes",u"magicNumber",u"status"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"commandTypes",b"commandTypes",u"magicNumber",b"magicNumber",u"status",b"status"]) -> None: ...
