# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpCommandType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpCommandType.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,proto/gRPCCommunication/GrpCommandType.proto\x12\x11gRPCCommunication*S\n\x0eGrpCommandType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\t\n\x05RESET\x10\x01\x12\x0e\n\nSTEP_INPUT\x10\x02\x12\x0f\n\x0bSTEP_OUTPUT\x10\x03\x12\x08\n\x04QUIT\x10\x04\x62\x06proto3')
)

_GRPCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='GrpCommandType',
  full_name='gRPCCommunication.GrpCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEP_INPUT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STEP_OUTPUT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUIT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=67,
  serialized_end=150,
)
_sym_db.RegisterEnumDescriptor(_GRPCOMMANDTYPE)

GrpCommandType = enum_type_wrapper.EnumTypeWrapper(_GRPCOMMANDTYPE)
CONNECT = 0
RESET = 1
STEP_INPUT = 2
STEP_OUTPUT = 3
QUIT = 4


DESCRIPTOR.enum_types_by_name['GrpCommandType'] = _GRPCOMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
