# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpcTrainingParameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.gRPCCommunication import GrpcParameter_pb2 as proto_dot_gRPCCommunication_dot_GrpcParameter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpcTrainingParameters.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n4proto/gRPCCommunication/GrpcTrainingParameters.proto\x12\x11gRPCCommunication\x1a+proto/gRPCCommunication/GrpcParameter.proto\"N\n\x16GrpcTrainingParameters\x12\x34\n\nparameters\x18\x01 \x03(\x0b\x32 .gRPCCommunication.GrpcParameterb\x06proto3')
  ,
  dependencies=[proto_dot_gRPCCommunication_dot_GrpcParameter__pb2.DESCRIPTOR,])




_GRPCTRAININGPARAMETERS = _descriptor.Descriptor(
  name='GrpcTrainingParameters',
  full_name='gRPCCommunication.GrpcTrainingParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parameters', full_name='gRPCCommunication.GrpcTrainingParameters.parameters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=198,
)

_GRPCTRAININGPARAMETERS.fields_by_name['parameters'].message_type = proto_dot_gRPCCommunication_dot_GrpcParameter__pb2._GRPCPARAMETER
DESCRIPTOR.message_types_by_name['GrpcTrainingParameters'] = _GRPCTRAININGPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcTrainingParameters = _reflection.GeneratedProtocolMessageType('GrpcTrainingParameters', (_message.Message,), {
  'DESCRIPTOR' : _GRPCTRAININGPARAMETERS,
  '__module__' : 'proto.gRPCCommunication.GrpcTrainingParameters_pb2'
  # @@protoc_insertion_point(class_scope:gRPCCommunication.GrpcTrainingParameters)
  })
_sym_db.RegisterMessage(GrpcTrainingParameters)


# @@protoc_insertion_point(module_scope)
