# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpcParameter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpcParameter.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n+proto/gRPCCommunication/GrpcParameter.proto\x12\x11gRPCCommunication\":\n\rGrpcParameter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\tb\x06proto3')
)




_GRPCPARAMETER = _descriptor.Descriptor(
  name='GrpcParameter',
  full_name='gRPCCommunication.GrpcParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='gRPCCommunication.GrpcParameter.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='gRPCCommunication.GrpcParameter.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='gRPCCommunication.GrpcParameter.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['GrpcParameter'] = _GRPCPARAMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcParameter = _reflection.GeneratedProtocolMessageType('GrpcParameter', (_message.Message,), {
  'DESCRIPTOR' : _GRPCPARAMETER,
  '__module__' : 'proto.gRPCCommunication.GrpcParameter_pb2'
  # @@protoc_insertion_point(class_scope:gRPCCommunication.GrpcParameter)
  })
_sym_db.RegisterMessage(GrpcParameter)


# @@protoc_insertion_point(module_scope)
