# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/gRPCCommunication/GrpcPPOSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/gRPCCommunication/GrpcPPOSettings.proto',
  package='gRPCCommunication',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n-proto/gRPCCommunication/GrpcPPOSettings.proto\x12\x11gRPCCommunication\"\xca\x02\n\x0fGrpcPPOSettings\x12\x11\n\tnumAction\x18\x01 \x01(\x05\x12\x13\n\x0bvalueFactor\x18\x02 \x01(\x02\x12\x15\n\rentropyFactor\x18\x03 \x01(\x02\x12\x0f\n\x07\x65psilon\x18\x04 \x01(\x02\x12\x14\n\x0clearningRate\x18\x05 \x01(\x02\x12\x19\n\x11learningRateDecay\x18\x06 \x01(\t\x12\x10\n\x08grapClip\x18\x07 \x01(\x02\x12\x18\n\x10loadEpisodeSaved\x18\x08 \x01(\x02\x12\x14\n\x0csavedEpisode\x18\t \x01(\x02\x12\x13\n\x0btimeHozizon\x18\n \x01(\x02\x12\x11\n\tbatchSize\x18\x0b \x01(\x02\x12\r\n\x05gamma\x18\x0c \x01(\x02\x12\x0b\n\x03lam\x18\r \x01(\x02\x12\r\n\x05\x65poch\x18\x0e \x01(\x05\x12\x0e\n\x06\x61\x63tors\x18\x0f \x01(\x05\x12\x11\n\tfinalStep\x18\x10 \x01(\x05\x62\x06proto3')
)




_GRPCPPOSETTINGS = _descriptor.Descriptor(
  name='GrpcPPOSettings',
  full_name='gRPCCommunication.GrpcPPOSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numAction', full_name='gRPCCommunication.GrpcPPOSettings.numAction', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='valueFactor', full_name='gRPCCommunication.GrpcPPOSettings.valueFactor', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entropyFactor', full_name='gRPCCommunication.GrpcPPOSettings.entropyFactor', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epsilon', full_name='gRPCCommunication.GrpcPPOSettings.epsilon', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learningRate', full_name='gRPCCommunication.GrpcPPOSettings.learningRate', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='learningRateDecay', full_name='gRPCCommunication.GrpcPPOSettings.learningRateDecay', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grapClip', full_name='gRPCCommunication.GrpcPPOSettings.grapClip', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loadEpisodeSaved', full_name='gRPCCommunication.GrpcPPOSettings.loadEpisodeSaved', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='savedEpisode', full_name='gRPCCommunication.GrpcPPOSettings.savedEpisode', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeHozizon', full_name='gRPCCommunication.GrpcPPOSettings.timeHozizon', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='gRPCCommunication.GrpcPPOSettings.batchSize', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamma', full_name='gRPCCommunication.GrpcPPOSettings.gamma', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lam', full_name='gRPCCommunication.GrpcPPOSettings.lam', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch', full_name='gRPCCommunication.GrpcPPOSettings.epoch', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actors', full_name='gRPCCommunication.GrpcPPOSettings.actors', index=14,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finalStep', full_name='gRPCCommunication.GrpcPPOSettings.finalStep', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=399,
)

DESCRIPTOR.message_types_by_name['GrpcPPOSettings'] = _GRPCPPOSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GrpcPPOSettings = _reflection.GeneratedProtocolMessageType('GrpcPPOSettings', (_message.Message,), {
  'DESCRIPTOR' : _GRPCPPOSETTINGS,
  '__module__' : 'proto.gRPCCommunication.GrpcPPOSettings_pb2'
  # @@protoc_insertion_point(class_scope:gRPCCommunication.GrpcPPOSettings)
  })
_sym_db.RegisterMessage(GrpcPPOSettings)


# @@protoc_insertion_point(module_scope)
