// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gRPCCommunication/GrpcCommunicator.proto

#include "proto/gRPCCommunication/GrpcCommunicator.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace gRPCCommunication {
}  // namespace gRPCCommunication
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto[] =
  "\n.proto/gRPCCommunication/GrpcCommunicat"
  "or.proto\022\021gRPCCommunication\032)proto/gRPCC"
  "ommunication/GrpcPackage.proto2c\n\020GrpcCo"
  "mmunicator\022O\n\013Communicate\022\036.gRPCCommunic"
  "ation.GrpcPackage\032\036.gRPCCommunication.Gr"
  "pcPackage\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_deps[1] = {
  &::descriptor_table_proto_2fgRPCCommunication_2fGrpcPackage_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_once;
static bool descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto = {
  &descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_initialized, descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto, "proto/gRPCCommunication/GrpcCommunicator.proto", 219,
  &descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_once, descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_sccs, descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto_deps, 0, 1,
  schemas, file_default_instances, TableStruct_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto::offsets,
  file_level_metadata_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto, 0, file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto, file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto), true);
namespace gRPCCommunication {

// @@protoc_insertion_point(namespace_scope)
}  // namespace gRPCCommunication
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
