// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/gRPCCommunication/GrpcCommunicator.proto
#ifndef GRPC_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto__INCLUDED
#define GRPC_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto__INCLUDED

#include "proto/gRPCCommunication/GrpcCommunicator.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace gRPCCommunication {

// The GrpcCommunicator service definition.
class GrpcCommunicator final {
 public:
  static constexpr char const* service_full_name() {
    return "gRPCCommunication.GrpcCommunicator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Communicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::gRPCCommunication::GrpcPackage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gRPCCommunication::GrpcPackage>> AsyncCommunicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gRPCCommunication::GrpcPackage>>(AsyncCommunicateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gRPCCommunication::GrpcPackage>> PrepareAsyncCommunicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::gRPCCommunication::GrpcPackage>>(PrepareAsyncCommunicateRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Communicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage* request, ::gRPCCommunication::GrpcPackage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Communicate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gRPCCommunication::GrpcPackage* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Communicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage* request, ::gRPCCommunication::GrpcPackage* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void Communicate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gRPCCommunication::GrpcPackage* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gRPCCommunication::GrpcPackage>* AsyncCommunicateRaw(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::gRPCCommunication::GrpcPackage>* PrepareAsyncCommunicateRaw(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Communicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::gRPCCommunication::GrpcPackage* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gRPCCommunication::GrpcPackage>> AsyncCommunicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gRPCCommunication::GrpcPackage>>(AsyncCommunicateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gRPCCommunication::GrpcPackage>> PrepareAsyncCommunicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::gRPCCommunication::GrpcPackage>>(PrepareAsyncCommunicateRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Communicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage* request, ::gRPCCommunication::GrpcPackage* response, std::function<void(::grpc::Status)>) override;
      void Communicate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gRPCCommunication::GrpcPackage* response, std::function<void(::grpc::Status)>) override;
      void Communicate(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage* request, ::gRPCCommunication::GrpcPackage* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void Communicate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::gRPCCommunication::GrpcPackage* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::gRPCCommunication::GrpcPackage>* AsyncCommunicateRaw(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::gRPCCommunication::GrpcPackage>* PrepareAsyncCommunicateRaw(::grpc::ClientContext* context, const ::gRPCCommunication::GrpcPackage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Communicate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Communicate(::grpc::ServerContext* context, const ::gRPCCommunication::GrpcPackage* request, ::gRPCCommunication::GrpcPackage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Communicate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommunicate(::grpc::ServerContext* context, ::gRPCCommunication::GrpcPackage* request, ::grpc::ServerAsyncResponseWriter< ::gRPCCommunication::GrpcPackage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Communicate<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Communicate() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::gRPCCommunication::GrpcPackage, ::gRPCCommunication::GrpcPackage>(
          [this](::grpc::ServerContext* context,
                 const ::gRPCCommunication::GrpcPackage* request,
                 ::gRPCCommunication::GrpcPackage* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Communicate(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_Communicate(
        ::grpc::experimental::MessageAllocator< ::gRPCCommunication::GrpcPackage, ::gRPCCommunication::GrpcPackage>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::gRPCCommunication::GrpcPackage, ::gRPCCommunication::GrpcPackage>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Communicate<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Communicate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Communicate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCommunicate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Communicate() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Communicate(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Communicate(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Communicate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Communicate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::gRPCCommunication::GrpcPackage, ::gRPCCommunication::GrpcPackage>(std::bind(&WithStreamedUnaryMethod_Communicate<BaseClass>::StreamedCommunicate, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Communicate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Communicate(::grpc::ServerContext* /*context*/, const ::gRPCCommunication::GrpcPackage* /*request*/, ::gRPCCommunication::GrpcPackage* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCommunicate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::gRPCCommunication::GrpcPackage,::gRPCCommunication::GrpcPackage>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Communicate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Communicate<Service > StreamedService;
};

}  // namespace gRPCCommunication


#endif  // GRPC_proto_2fgRPCCommunication_2fGrpcCommunicator_2eproto__INCLUDED
