// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gRPCCommunication/GrpCommandType.proto

#include "proto/gRPCCommunication/GrpCommandType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace gRPCCommunication {
}  // namespace gRPCCommunication
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_proto_2fgRPCCommunication_2fGrpCommandType_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpCommandType_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpCommandType_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fgRPCCommunication_2fGrpCommandType_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpCommandType_2eproto[] =
  "\n,proto/gRPCCommunication/GrpCommandType"
  ".proto\022\021gRPCCommunication*S\n\016GrpCommandT"
  "ype\022\013\n\007CONNECT\020\000\022\t\n\005RESET\020\001\022\016\n\nSTEP_INPU"
  "T\020\002\022\017\n\013STEP_OUTPUT\020\003\022\010\n\004QUIT\020\004b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_once;
static bool descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto = {
  &descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_initialized, descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpCommandType_2eproto, "proto/gRPCCommunication/GrpCommandType.proto", 158,
  &descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_once, descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_sccs, descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_proto_2fgRPCCommunication_2fGrpCommandType_2eproto::offsets,
  file_level_metadata_proto_2fgRPCCommunication_2fGrpCommandType_2eproto, 0, file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpCommandType_2eproto, file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpCommandType_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fgRPCCommunication_2fGrpCommandType_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto), true);
namespace gRPCCommunication {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GrpCommandType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fgRPCCommunication_2fGrpCommandType_2eproto);
  return file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpCommandType_2eproto[0];
}
bool GrpCommandType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace gRPCCommunication
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
