// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gRPCCommunication/GrpcProtoType.proto

#include "proto/gRPCCommunication/GrpcProtoType.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace gRPCCommunication {
class GrpcProtoTypeDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GrpcProtoType> _instance;
} _GrpcProtoType_default_instance_;
}  // namespace gRPCCommunication
static void InitDefaultsscc_info_GrpcProtoType_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gRPCCommunication::_GrpcProtoType_default_instance_;
    new (ptr) ::gRPCCommunication::GrpcProtoType();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gRPCCommunication::GrpcProtoType::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GrpcProtoType_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_GrpcProtoType_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcProtoType, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcProtoType, type_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcProtoType, repeated_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::gRPCCommunication::GrpcProtoType)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::gRPCCommunication::_GrpcProtoType_default_instance_),
};

const char descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto[] =
  "\n+proto/gRPCCommunication/GrpcProtoType."
  "proto\022\021gRPCCommunication\"U\n\rGrpcProtoTyp"
  "e\0222\n\004type\030\001 \001(\0162$.gRPCCommunication.Grpc"
  "BaseProtoType\022\020\n\010repeated\030\002 \001(\010*\307\001\n\021Grpc"
  "BaseProtoType\022\n\n\006DOUBLE\020\000\022\t\n\005FLOAT\020\001\022\t\n\005"
  "INT32\020\002\022\t\n\005INT64\020\003\022\n\n\006UINT32\020\004\022\n\n\006UINT64"
  "\020\005\022\n\n\006SINT32\020\006\022\n\n\006SINT64\020\007\022\013\n\007FIXED32\020\010\022"
  "\013\n\007FIXED64\020\t\022\014\n\010SFIXED32\020\n\022\014\n\010SFIXED64\020\013"
  "\022\010\n\004BOOL\020\014\022\n\n\006STRING\020\r\022\t\n\005BYTES\020\016b\006proto"
  "3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_sccs[1] = {
  &scc_info_GrpcProtoType_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_once;
static bool descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto = {
  &descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_initialized, descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto, "proto/gRPCCommunication/GrpcProtoType.proto", 361,
  &descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_once, descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_sccs, descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto::offsets,
  file_level_metadata_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto, 1, file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto, file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto), true);
namespace gRPCCommunication {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GrpcBaseProtoType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto);
  return file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto[0];
}
bool GrpcBaseProtoType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void GrpcProtoType::InitAsDefaultInstance() {
}
class GrpcProtoType::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GrpcProtoType::kTypeFieldNumber;
const int GrpcProtoType::kRepeatedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GrpcProtoType::GrpcProtoType()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gRPCCommunication.GrpcProtoType)
}
GrpcProtoType::GrpcProtoType(const GrpcProtoType& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&repeated_) -
    reinterpret_cast<char*>(&type_)) + sizeof(repeated_));
  // @@protoc_insertion_point(copy_constructor:gRPCCommunication.GrpcProtoType)
}

void GrpcProtoType::SharedCtor() {
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&repeated_) -
      reinterpret_cast<char*>(&type_)) + sizeof(repeated_));
}

GrpcProtoType::~GrpcProtoType() {
  // @@protoc_insertion_point(destructor:gRPCCommunication.GrpcProtoType)
  SharedDtor();
}

void GrpcProtoType::SharedDtor() {
}

void GrpcProtoType::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GrpcProtoType& GrpcProtoType::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GrpcProtoType_proto_2fgRPCCommunication_2fGrpcProtoType_2eproto.base);
  return *internal_default_instance();
}


void GrpcProtoType::Clear() {
// @@protoc_insertion_point(message_clear_start:gRPCCommunication.GrpcProtoType)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&repeated_) -
      reinterpret_cast<char*>(&type_)) + sizeof(repeated_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GrpcProtoType::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .gRPCCommunication.GrpcBaseProtoType type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          set_type(static_cast<::gRPCCommunication::GrpcBaseProtoType>(val));
        } else goto handle_unusual;
        continue;
      // bool repeated = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          repeated_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GrpcProtoType::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:gRPCCommunication.GrpcProtoType)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .gRPCCommunication.GrpcBaseProtoType type = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {
          int value = 0;
          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   int, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::gRPCCommunication::GrpcBaseProtoType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool repeated = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (16 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   bool, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_BOOL>(
                 input, &repeated_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gRPCCommunication.GrpcProtoType)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gRPCCommunication.GrpcProtoType)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GrpcProtoType::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gRPCCommunication.GrpcProtoType)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .gRPCCommunication.GrpcBaseProtoType type = 1;
  if (this->type() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // bool repeated = 2;
  if (this->repeated() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBool(2, this->repeated(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gRPCCommunication.GrpcProtoType)
}

::PROTOBUF_NAMESPACE_ID::uint8* GrpcProtoType::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gRPCCommunication.GrpcProtoType)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .gRPCCommunication.GrpcBaseProtoType type = 1;
  if (this->type() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // bool repeated = 2;
  if (this->repeated() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->repeated(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gRPCCommunication.GrpcProtoType)
  return target;
}

size_t GrpcProtoType::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gRPCCommunication.GrpcProtoType)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .gRPCCommunication.GrpcBaseProtoType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->type());
  }

  // bool repeated = 2;
  if (this->repeated() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GrpcProtoType::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gRPCCommunication.GrpcProtoType)
  GOOGLE_DCHECK_NE(&from, this);
  const GrpcProtoType* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GrpcProtoType>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gRPCCommunication.GrpcProtoType)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gRPCCommunication.GrpcProtoType)
    MergeFrom(*source);
  }
}

void GrpcProtoType::MergeFrom(const GrpcProtoType& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gRPCCommunication.GrpcProtoType)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.repeated() != 0) {
    set_repeated(from.repeated());
  }
}

void GrpcProtoType::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gRPCCommunication.GrpcProtoType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GrpcProtoType::CopyFrom(const GrpcProtoType& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gRPCCommunication.GrpcProtoType)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GrpcProtoType::IsInitialized() const {
  return true;
}

void GrpcProtoType::Swap(GrpcProtoType* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GrpcProtoType::InternalSwap(GrpcProtoType* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(type_, other->type_);
  swap(repeated_, other->repeated_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GrpcProtoType::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace gRPCCommunication
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gRPCCommunication::GrpcProtoType* Arena::CreateMaybeMessage< ::gRPCCommunication::GrpcProtoType >(Arena* arena) {
  return Arena::CreateInternal< ::gRPCCommunication::GrpcProtoType >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
