// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gRPCCommunication/GrpcPPOSettings.proto

#include "proto/gRPCCommunication/GrpcPPOSettings.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace gRPCCommunication {
class GrpcPPOSettingsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<GrpcPPOSettings> _instance;
} _GrpcPPOSettings_default_instance_;
}  // namespace gRPCCommunication
static void InitDefaultsscc_info_GrpcPPOSettings_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gRPCCommunication::_GrpcPPOSettings_default_instance_;
    new (ptr) ::gRPCCommunication::GrpcPPOSettings();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gRPCCommunication::GrpcPPOSettings::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_GrpcPPOSettings_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsscc_info_GrpcPPOSettings_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, numaction_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, valuefactor_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, entropyfactor_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, epsilon_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, learningrate_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, learningratedecay_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, grapclip_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, loadepisodesaved_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, savedepisode_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, timehozizon_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, batchsize_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, gamma_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, lam_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, epoch_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, actors_),
  PROTOBUF_FIELD_OFFSET(::gRPCCommunication::GrpcPPOSettings, finalstep_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::gRPCCommunication::GrpcPPOSettings)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::gRPCCommunication::_GrpcPPOSettings_default_instance_),
};

const char descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto[] =
  "\n-proto/gRPCCommunication/GrpcPPOSetting"
  "s.proto\022\021gRPCCommunication\"\312\002\n\017GrpcPPOSe"
  "ttings\022\021\n\tnumAction\030\001 \001(\005\022\023\n\013valueFactor"
  "\030\002 \001(\002\022\025\n\rentropyFactor\030\003 \001(\002\022\017\n\007epsilon"
  "\030\004 \001(\002\022\024\n\014learningRate\030\005 \001(\002\022\031\n\021learning"
  "RateDecay\030\006 \001(\t\022\020\n\010grapClip\030\007 \001(\002\022\030\n\020loa"
  "dEpisodeSaved\030\010 \001(\002\022\024\n\014savedEpisode\030\t \001("
  "\002\022\023\n\013timeHozizon\030\n \001(\002\022\021\n\tbatchSize\030\013 \001("
  "\002\022\r\n\005gamma\030\014 \001(\002\022\013\n\003lam\030\r \001(\002\022\r\n\005epoch\030\016"
  " \001(\005\022\016\n\006actors\030\017 \001(\005\022\021\n\tfinalStep\030\020 \001(\005b"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_sccs[1] = {
  &scc_info_GrpcPPOSettings_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_once;
static bool descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto = {
  &descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_initialized, descriptor_table_protodef_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto, "proto/gRPCCommunication/GrpcPPOSettings.proto", 407,
  &descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_once, descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_sccs, descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto::offsets,
  file_level_metadata_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto, 1, file_level_enum_descriptors_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto, file_level_service_descriptors_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto), true);
namespace gRPCCommunication {

// ===================================================================

void GrpcPPOSettings::InitAsDefaultInstance() {
}
class GrpcPPOSettings::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GrpcPPOSettings::kNumActionFieldNumber;
const int GrpcPPOSettings::kValueFactorFieldNumber;
const int GrpcPPOSettings::kEntropyFactorFieldNumber;
const int GrpcPPOSettings::kEpsilonFieldNumber;
const int GrpcPPOSettings::kLearningRateFieldNumber;
const int GrpcPPOSettings::kLearningRateDecayFieldNumber;
const int GrpcPPOSettings::kGrapClipFieldNumber;
const int GrpcPPOSettings::kLoadEpisodeSavedFieldNumber;
const int GrpcPPOSettings::kSavedEpisodeFieldNumber;
const int GrpcPPOSettings::kTimeHozizonFieldNumber;
const int GrpcPPOSettings::kBatchSizeFieldNumber;
const int GrpcPPOSettings::kGammaFieldNumber;
const int GrpcPPOSettings::kLamFieldNumber;
const int GrpcPPOSettings::kEpochFieldNumber;
const int GrpcPPOSettings::kActorsFieldNumber;
const int GrpcPPOSettings::kFinalStepFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GrpcPPOSettings::GrpcPPOSettings()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gRPCCommunication.GrpcPPOSettings)
}
GrpcPPOSettings::GrpcPPOSettings(const GrpcPPOSettings& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  learningratedecay_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from.learningratedecay().size() > 0) {
    learningratedecay_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.learningratedecay_);
  }
  ::memcpy(&numaction_, &from.numaction_,
    static_cast<size_t>(reinterpret_cast<char*>(&finalstep_) -
    reinterpret_cast<char*>(&numaction_)) + sizeof(finalstep_));
  // @@protoc_insertion_point(copy_constructor:gRPCCommunication.GrpcPPOSettings)
}

void GrpcPPOSettings::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_GrpcPPOSettings_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto.base);
  learningratedecay_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&numaction_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&finalstep_) -
      reinterpret_cast<char*>(&numaction_)) + sizeof(finalstep_));
}

GrpcPPOSettings::~GrpcPPOSettings() {
  // @@protoc_insertion_point(destructor:gRPCCommunication.GrpcPPOSettings)
  SharedDtor();
}

void GrpcPPOSettings::SharedDtor() {
  learningratedecay_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void GrpcPPOSettings::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GrpcPPOSettings& GrpcPPOSettings::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_GrpcPPOSettings_proto_2fgRPCCommunication_2fGrpcPPOSettings_2eproto.base);
  return *internal_default_instance();
}


void GrpcPPOSettings::Clear() {
// @@protoc_insertion_point(message_clear_start:gRPCCommunication.GrpcPPOSettings)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  learningratedecay_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&numaction_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&finalstep_) -
      reinterpret_cast<char*>(&numaction_)) + sizeof(finalstep_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GrpcPPOSettings::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 numAction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          numaction_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float valueFactor = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          valuefactor_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float entropyFactor = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          entropyfactor_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float epsilon = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          epsilon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float learningRate = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          learningrate_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // string learningRateDecay = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(mutable_learningratedecay(), ptr, ctx, "gRPCCommunication.GrpcPPOSettings.learningRateDecay");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float grapClip = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61)) {
          grapclip_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float loadEpisodeSaved = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          loadepisodesaved_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float savedEpisode = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 77)) {
          savedepisode_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float timeHozizon = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 85)) {
          timehozizon_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float batchSize = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 93)) {
          batchsize_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float gamma = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 101)) {
          gamma_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float lam = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 109)) {
          lam_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // int32 epoch = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 112)) {
          epoch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 actors = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          actors_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 finalStep = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 128)) {
          finalstep_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GrpcPPOSettings::MergePartialFromCodedStream(
    ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::PROTOBUF_NAMESPACE_ID::uint32 tag;
  // @@protoc_insertion_point(parse_start:gRPCCommunication.GrpcPPOSettings)
  for (;;) {
    ::std::pair<::PROTOBUF_NAMESPACE_ID::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 numAction = 1;
      case 1: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (8 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &numaction_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float valueFactor = 2;
      case 2: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (21 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &valuefactor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float entropyFactor = 3;
      case 3: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (29 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &entropyfactor_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float epsilon = 4;
      case 4: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (37 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &epsilon_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float learningRate = 5;
      case 5: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (45 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &learningrate_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string learningRateDecay = 6;
      case 6: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (50 & 0xFF)) {
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadString(
                input, this->mutable_learningratedecay()));
          DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
            this->learningratedecay().data(), static_cast<int>(this->learningratedecay().length()),
            ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE,
            "gRPCCommunication.GrpcPPOSettings.learningRateDecay"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float grapClip = 7;
      case 7: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (61 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &grapclip_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float loadEpisodeSaved = 8;
      case 8: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (69 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &loadepisodesaved_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float savedEpisode = 9;
      case 9: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (77 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &savedepisode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float timeHozizon = 10;
      case 10: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (85 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &timehozizon_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float batchSize = 11;
      case 11: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (93 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &batchsize_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float gamma = 12;
      case 12: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (101 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &gamma_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float lam = 13;
      case 13: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (109 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   float, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &lam_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 epoch = 14;
      case 14: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (112 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &epoch_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 actors = 15;
      case 15: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (120 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &actors_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 finalStep = 16;
      case 16: {
        if (static_cast< ::PROTOBUF_NAMESPACE_ID::uint8>(tag) == (128 & 0xFF)) {

          DO_((::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::ReadPrimitive<
                   ::PROTOBUF_NAMESPACE_ID::int32, ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32>(
                 input, &finalstep_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gRPCCommunication.GrpcPPOSettings)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gRPCCommunication.GrpcPPOSettings)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GrpcPPOSettings::SerializeWithCachedSizes(
    ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gRPCCommunication.GrpcPPOSettings)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 numAction = 1;
  if (this->numaction() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(1, this->numaction(), output);
  }

  // float valueFactor = 2;
  if (!(this->valuefactor() <= 0 && this->valuefactor() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(2, this->valuefactor(), output);
  }

  // float entropyFactor = 3;
  if (!(this->entropyfactor() <= 0 && this->entropyfactor() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(3, this->entropyfactor(), output);
  }

  // float epsilon = 4;
  if (!(this->epsilon() <= 0 && this->epsilon() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(4, this->epsilon(), output);
  }

  // float learningRate = 5;
  if (!(this->learningrate() <= 0 && this->learningrate() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(5, this->learningrate(), output);
  }

  // string learningRateDecay = 6;
  if (this->learningratedecay().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->learningratedecay().data(), static_cast<int>(this->learningratedecay().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gRPCCommunication.GrpcPPOSettings.learningRateDecay");
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->learningratedecay(), output);
  }

  // float grapClip = 7;
  if (!(this->grapclip() <= 0 && this->grapclip() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(7, this->grapclip(), output);
  }

  // float loadEpisodeSaved = 8;
  if (!(this->loadepisodesaved() <= 0 && this->loadepisodesaved() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(8, this->loadepisodesaved(), output);
  }

  // float savedEpisode = 9;
  if (!(this->savedepisode() <= 0 && this->savedepisode() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(9, this->savedepisode(), output);
  }

  // float timeHozizon = 10;
  if (!(this->timehozizon() <= 0 && this->timehozizon() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(10, this->timehozizon(), output);
  }

  // float batchSize = 11;
  if (!(this->batchsize() <= 0 && this->batchsize() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(11, this->batchsize(), output);
  }

  // float gamma = 12;
  if (!(this->gamma() <= 0 && this->gamma() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(12, this->gamma(), output);
  }

  // float lam = 13;
  if (!(this->lam() <= 0 && this->lam() >= 0)) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloat(13, this->lam(), output);
  }

  // int32 epoch = 14;
  if (this->epoch() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(14, this->epoch(), output);
  }

  // int32 actors = 15;
  if (this->actors() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(15, this->actors(), output);
  }

  // int32 finalStep = 16;
  if (this->finalstep() != 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32(16, this->finalstep(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gRPCCommunication.GrpcPPOSettings)
}

::PROTOBUF_NAMESPACE_ID::uint8* GrpcPPOSettings::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gRPCCommunication.GrpcPPOSettings)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 numAction = 1;
  if (this->numaction() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->numaction(), target);
  }

  // float valueFactor = 2;
  if (!(this->valuefactor() <= 0 && this->valuefactor() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->valuefactor(), target);
  }

  // float entropyFactor = 3;
  if (!(this->entropyfactor() <= 0 && this->entropyfactor() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->entropyfactor(), target);
  }

  // float epsilon = 4;
  if (!(this->epsilon() <= 0 && this->epsilon() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->epsilon(), target);
  }

  // float learningRate = 5;
  if (!(this->learningrate() <= 0 && this->learningrate() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->learningrate(), target);
  }

  // string learningRateDecay = 6;
  if (this->learningratedecay().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->learningratedecay().data(), static_cast<int>(this->learningratedecay().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gRPCCommunication.GrpcPPOSettings.learningRateDecay");
    target =
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteStringToArray(
        6, this->learningratedecay(), target);
  }

  // float grapClip = 7;
  if (!(this->grapclip() <= 0 && this->grapclip() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(7, this->grapclip(), target);
  }

  // float loadEpisodeSaved = 8;
  if (!(this->loadepisodesaved() <= 0 && this->loadepisodesaved() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->loadepisodesaved(), target);
  }

  // float savedEpisode = 9;
  if (!(this->savedepisode() <= 0 && this->savedepisode() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(9, this->savedepisode(), target);
  }

  // float timeHozizon = 10;
  if (!(this->timehozizon() <= 0 && this->timehozizon() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(10, this->timehozizon(), target);
  }

  // float batchSize = 11;
  if (!(this->batchsize() <= 0 && this->batchsize() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(11, this->batchsize(), target);
  }

  // float gamma = 12;
  if (!(this->gamma() <= 0 && this->gamma() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(12, this->gamma(), target);
  }

  // float lam = 13;
  if (!(this->lam() <= 0 && this->lam() >= 0)) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(13, this->lam(), target);
  }

  // int32 epoch = 14;
  if (this->epoch() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(14, this->epoch(), target);
  }

  // int32 actors = 15;
  if (this->actors() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(15, this->actors(), target);
  }

  // int32 finalStep = 16;
  if (this->finalstep() != 0) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(16, this->finalstep(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gRPCCommunication.GrpcPPOSettings)
  return target;
}

size_t GrpcPPOSettings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gRPCCommunication.GrpcPPOSettings)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string learningRateDecay = 6;
  if (this->learningratedecay().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->learningratedecay());
  }

  // int32 numAction = 1;
  if (this->numaction() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->numaction());
  }

  // float valueFactor = 2;
  if (!(this->valuefactor() <= 0 && this->valuefactor() >= 0)) {
    total_size += 1 + 4;
  }

  // float entropyFactor = 3;
  if (!(this->entropyfactor() <= 0 && this->entropyfactor() >= 0)) {
    total_size += 1 + 4;
  }

  // float epsilon = 4;
  if (!(this->epsilon() <= 0 && this->epsilon() >= 0)) {
    total_size += 1 + 4;
  }

  // float learningRate = 5;
  if (!(this->learningrate() <= 0 && this->learningrate() >= 0)) {
    total_size += 1 + 4;
  }

  // float grapClip = 7;
  if (!(this->grapclip() <= 0 && this->grapclip() >= 0)) {
    total_size += 1 + 4;
  }

  // float loadEpisodeSaved = 8;
  if (!(this->loadepisodesaved() <= 0 && this->loadepisodesaved() >= 0)) {
    total_size += 1 + 4;
  }

  // float savedEpisode = 9;
  if (!(this->savedepisode() <= 0 && this->savedepisode() >= 0)) {
    total_size += 1 + 4;
  }

  // float timeHozizon = 10;
  if (!(this->timehozizon() <= 0 && this->timehozizon() >= 0)) {
    total_size += 1 + 4;
  }

  // float batchSize = 11;
  if (!(this->batchsize() <= 0 && this->batchsize() >= 0)) {
    total_size += 1 + 4;
  }

  // float gamma = 12;
  if (!(this->gamma() <= 0 && this->gamma() >= 0)) {
    total_size += 1 + 4;
  }

  // float lam = 13;
  if (!(this->lam() <= 0 && this->lam() >= 0)) {
    total_size += 1 + 4;
  }

  // int32 epoch = 14;
  if (this->epoch() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->epoch());
  }

  // int32 actors = 15;
  if (this->actors() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->actors());
  }

  // int32 finalStep = 16;
  if (this->finalstep() != 0) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->finalstep());
  }

  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GrpcPPOSettings::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gRPCCommunication.GrpcPPOSettings)
  GOOGLE_DCHECK_NE(&from, this);
  const GrpcPPOSettings* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<GrpcPPOSettings>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gRPCCommunication.GrpcPPOSettings)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gRPCCommunication.GrpcPPOSettings)
    MergeFrom(*source);
  }
}

void GrpcPPOSettings::MergeFrom(const GrpcPPOSettings& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gRPCCommunication.GrpcPPOSettings)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.learningratedecay().size() > 0) {

    learningratedecay_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.learningratedecay_);
  }
  if (from.numaction() != 0) {
    set_numaction(from.numaction());
  }
  if (!(from.valuefactor() <= 0 && from.valuefactor() >= 0)) {
    set_valuefactor(from.valuefactor());
  }
  if (!(from.entropyfactor() <= 0 && from.entropyfactor() >= 0)) {
    set_entropyfactor(from.entropyfactor());
  }
  if (!(from.epsilon() <= 0 && from.epsilon() >= 0)) {
    set_epsilon(from.epsilon());
  }
  if (!(from.learningrate() <= 0 && from.learningrate() >= 0)) {
    set_learningrate(from.learningrate());
  }
  if (!(from.grapclip() <= 0 && from.grapclip() >= 0)) {
    set_grapclip(from.grapclip());
  }
  if (!(from.loadepisodesaved() <= 0 && from.loadepisodesaved() >= 0)) {
    set_loadepisodesaved(from.loadepisodesaved());
  }
  if (!(from.savedepisode() <= 0 && from.savedepisode() >= 0)) {
    set_savedepisode(from.savedepisode());
  }
  if (!(from.timehozizon() <= 0 && from.timehozizon() >= 0)) {
    set_timehozizon(from.timehozizon());
  }
  if (!(from.batchsize() <= 0 && from.batchsize() >= 0)) {
    set_batchsize(from.batchsize());
  }
  if (!(from.gamma() <= 0 && from.gamma() >= 0)) {
    set_gamma(from.gamma());
  }
  if (!(from.lam() <= 0 && from.lam() >= 0)) {
    set_lam(from.lam());
  }
  if (from.epoch() != 0) {
    set_epoch(from.epoch());
  }
  if (from.actors() != 0) {
    set_actors(from.actors());
  }
  if (from.finalstep() != 0) {
    set_finalstep(from.finalstep());
  }
}

void GrpcPPOSettings::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gRPCCommunication.GrpcPPOSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GrpcPPOSettings::CopyFrom(const GrpcPPOSettings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gRPCCommunication.GrpcPPOSettings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GrpcPPOSettings::IsInitialized() const {
  return true;
}

void GrpcPPOSettings::Swap(GrpcPPOSettings* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GrpcPPOSettings::InternalSwap(GrpcPPOSettings* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  learningratedecay_.Swap(&other->learningratedecay_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(numaction_, other->numaction_);
  swap(valuefactor_, other->valuefactor_);
  swap(entropyfactor_, other->entropyfactor_);
  swap(epsilon_, other->epsilon_);
  swap(learningrate_, other->learningrate_);
  swap(grapclip_, other->grapclip_);
  swap(loadepisodesaved_, other->loadepisodesaved_);
  swap(savedepisode_, other->savedepisode_);
  swap(timehozizon_, other->timehozizon_);
  swap(batchsize_, other->batchsize_);
  swap(gamma_, other->gamma_);
  swap(lam_, other->lam_);
  swap(epoch_, other->epoch_);
  swap(actors_, other->actors_);
  swap(finalstep_, other->finalstep_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GrpcPPOSettings::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace gRPCCommunication
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gRPCCommunication::GrpcPPOSettings* Arena::CreateMaybeMessage< ::gRPCCommunication::GrpcPPOSettings >(Arena* arena) {
  return Arena::CreateInternal< ::gRPCCommunication::GrpcPPOSettings >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
